### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by rvdblom** [ChrisTerBeke/homey-enphase#3]
Hello,

is the app working already, i am unable to install with the cli method.
could you point my in the right direction or could I be of any kind of help?

kind regards,
Richard

**Comment by ChrisTerBeke** [comment]
Hi,

The app is running on my Homey, but it's not published in the App Store yet (we're waiting for the manufacturer Enphase to collaborate given their tight API rate restrictions).

To get it to run, you can indeed use `homey app run`, but you need an `env.json` file in the root directory that contains the needed API credentials.

```json
{
  "CLIENT_ID": "XXXX",
  "CLIENT_SECRET": "XXXX",
  "API_KEY": "XXXX"
}
```

In order to get the `CLIENT_ID` and `CLIENT_SECRET`, you need to go to the [Enphase Developer portal](https://developer-v4.enphase.com) and register for a free developer account. This free account only allows for 1 device to access the API once every 15 minutes, otherwise you hit the before mentioned rate limit. The `API_KEY` you can grab from the Enphase Enlighten app (menu -> account -> access control -> api settings).

**Comment by rvdblom** [comment]
hi,

Thanks, that worked altough i had to run npm install homey-oauth2app 

its working now! looks great! thanks for your work! hope you can publish soon in the app-store so more user can enjoy it.

**Comment by ChrisTerBeke** [comment]
Great to hear! Running `npm ci` in the root directory will also work, this installs all needed dependencies. Hopefully we can get it published soon indeed. I'm also working on a 'community version' that uses the local Envoy API, but that won't work on Homey Cloud.
